# Generated by Django 4.2.7 on 2026-07-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curriculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("enviado", "Enviado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "escolaridade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fundamental", "Ensino Fundamental"),
                            ("medio", "Ensino Médio"),
                            ("tecnico", "Curso Técnico"),
                            ("faculdade", "Faculdade"),
                            ("pos_graduacao", "Pós-graduação"),
                        ],
                        max_length=20,
                        verbose_name="Escolaridade",
                    ),
                ),
                (
                    "instituicao_escolaridade",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Instituição"
                    ),
                ),
                (
                    "curso_escolaridade",
                    models.CharField(blank=True, max_length=200, verbose_name="Curso"),
                ),
                (
                    "ano_conclusao_escolaridade",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano de conclusão"
                    ),
                ),
                (
                    "cnh",
                    models.CharField(
                        choices=[
                            ("nao_possui", "Não possui"),
                            ("A", "Categoria A"),
                            ("B", "Categoria B"),
                            ("AB", "Categoria AB"),
                            ("C", "Categoria C"),
                            ("D", "Categoria D"),
                            ("E", "Categoria E"),
                        ],
                        default="nao_possui",
                        max_length=20,
                        verbose_name="CNH",
                    ),
                ),
                (
                    "veiculo_proprio",
                    models.BooleanField(default=False, verbose_name="Veículo próprio"),
                ),
                (
                    "objetivo_profissional",
                    models.TextField(blank=True, verbose_name="Objetivo profissional"),
                ),
                (
                    "sem_experiencia",
                    models.BooleanField(
                        default=False, verbose_name="Sem experiência profissional"
                    ),
                ),
                (
                    "sem_cursos",
                    models.BooleanField(default=False, verbose_name="Sem cursos"),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "etapa_atual",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Etapa atual"
                    ),
                ),
                (
                    "pdf_arquivo",
                    models.FileField(
                        blank=True, upload_to="curriculos/pdf/", verbose_name="PDF"
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do pagamento"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de envio"
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor pago",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculo",
                        to="clientes.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currículo",
                "verbose_name_plural": "Currículos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ExperienciaProfissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=200, verbose_name="Empresa")),
                ("cargo", models.CharField(max_length=200, verbose_name="Cargo")),
                ("periodo", models.CharField(max_length=100, verbose_name="Período")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, verbose_name="Descrição das atividades"
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "curriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencias",
                        to="curriculos.curriculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiência Profissional",
                "verbose_name_plural": "Experiências Profissionais",
                "ordering": ["ordem", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do curso"),
                ),
                (
                    "instituicao",
                    models.CharField(max_length=200, verbose_name="Instituição"),
                ),
                (
                    "carga_horaria",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Carga horária"
                    ),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano"
                    ),
                ),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                (
                    "curriculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos",
                        to="curriculos.curriculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
                "ordering": ["ordem", "-id"],
            },
        ),
    ]
