# Generated by Django 5.1.7 on 2026-07-12 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("curriculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculo",
            name="vendedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="curriculos",
                to="accounts.vendedor",
                verbose_name="Vendedor",
            ),
        ),
    ]
