# Generated by Django 5.1.7 on 2026-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculos", "0002_curriculo_vendedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculo",
            name="habilidades",
            field=models.TextField(
                blank=True,
                help_text="Uma habilidade por linha.",
                verbose_name="Habilidades",
            ),
        ),
        migrations.AlterField(
            model_name="curriculo",
            name="objetivo_profissional",
            field=models.TextField(
                blank=True,
                help_text="Texto livre para a pessoa se apresentar (aparece no currículo).",
                verbose_name="Sobre mim",
            ),
        ),
    ]
