# Generated by Django 5.1.7 on 2026-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curriculos", "0003_habilidades_sobre_mim"),
    ]

    operations = [
        migrations.AddField(
            model_name="curriculo",
            name="sobre_mim",
            field=models.TextField(
                blank=True,
                help_text="Texto livre para a pessoa se apresentar.",
                verbose_name="Sobre mim",
            ),
        ),
        migrations.AddField(
            model_name="curriculo",
            name="tema",
            field=models.CharField(
                choices=[
                    ("azul", "Azul — Profissional"),
                    ("verde", "Verde — Moderno"),
                    ("roxo", "Roxo — Elegante"),
                ],
                default="azul",
                max_length=20,
                verbose_name="Cor do currículo",
            ),
        ),
        migrations.AlterField(
            model_name="curriculo",
            name="objetivo_profissional",
            field=models.TextField(
                blank=True,
                help_text="Objetivo de carreira em poucas linhas.",
                verbose_name="Objetivo profissional",
            ),
        ),
        migrations.AlterField(
            model_name="curso",
            name="instituicao",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Instituição"
            ),
        ),
    ]
