# Generated by Django 5.1.7 on 2026-07-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_publico",
                    models.CharField(max_length=120, verbose_name="Nome público"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=80, unique=True, verbose_name="Slug da página"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        help_text="Somente números, com DDD. Ex: 31988702824",
                        max_length=20,
                        verbose_name="WhatsApp",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendedor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
                "ordering": ["nome_publico"],
            },
        ),
    ]
