# Generated by Django 4.2.7 on 2026-07-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solteiro", "Solteiro(a)"),
                            ("casado", "Casado(a)"),
                            ("divorciado", "Divorciado(a)"),
                            ("viuvo", "Viúvo(a)"),
                            ("uniao_estavel", "União Estável"),
                        ],
                        max_length=20,
                        verbose_name="Estado civil",
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "bairro",
                    models.CharField(blank=True, max_length=100, verbose_name="Bairro"),
                ),
                (
                    "ano_nascimento",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano de nascimento"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-criado_em"],
            },
        ),
    ]
