# Generated by Django 5.1.7 on 2026-07-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Foto 3x4 ou retrato (opcional)",
                null=True,
                upload_to="clientes/fotos/",
                verbose_name="Foto",
            ),
        ),
    ]
